name: NoSpawner
version: ${project.version}
main: io.github.portlek.nospawner.NoSpawner
authors: [portlek]

commands:
  removespawner:
    permission: nospawner.command
    permission-message: No permission
    description: Delete all spawners that are in loaded chunks.
    usage: /removespawner
    aliases:
      - ss